Hw multithreading
Ilya-brinchuk/jv-multithreading-01 pull request #1
Opened 2021-02-22 15:30 UTC by Ilya-brinchuk

2021-02-22 16:03 UTC, oleksandrdziubiuk approved these changes

2021-02-22 16:03 UTC, oleksandrdziubiuk commented on pom.xml
>  </project>
не має нового рядка

2021-02-22 16:03 UTC, oleksandrdziubiuk commented on src/main/java/MyRunnable.java
> +
лишній пробіл

2021-02-22 16:03 UTC, oleksandrdziubiuk commented on src/main/java/MyThread.java
> +
так само

2021-02-23 08:38 UTC, RomanDubovskyi requested changes

2021-02-23 08:38 UTC, RomanDubovskyi commented on pom.xml
> +                    <version>3.3.1</version>
do we need war plugin?

2021-02-23 08:38 UTC, RomanDubovskyi commented on src/main/java/Main.java
> +        new Thread(myThread).start();
```suggestion
        MyThread myThread = new MyThread(counter);
        myThread.start();
```

2021-02-23 08:38 UTC, RomanDubovskyi commented on src/main/java/MyRunnable.java
> +    private static final String PATH_FILE = "src/main/resources/test.txt";
```suggestion
    private static final Logger logger = Logger.getLogger(MyRunnable.class);
```
we don't need this if we have logger

2021-02-23 08:38 UTC, RomanDubovskyi commented on src/main/java/Counter.java
> +        count++;
```suggestion
    public int increment() {
      return  count++;
```
that'll make the code shorter

2021-02-23 08:38 UTC, RomanDubovskyi commented on src/main/java/MyRunnable.java
> +                Files.write(Paths.get(PATH_FILE), data.getBytes(), StandardOpenOption.APPEND);
make the logger write data to file
```suggestion
```

2021-02-23 08:38 UTC, RomanDubovskyi commented on src/main/java/MyThread.java
> +    public void run() {
same here

2021-02-23 08:38 UTC, RomanDubovskyi commented on src/main/resources/log-file.log
> +
missing empty line at the end of the file

2021-02-23 08:38 UTC, RomanDubovskyi commented on src/main/resources/test.txt
> +Thread-1 value = 0
one file is enough, we don;t need this one

2021-02-23 11:09 UTC, RomanDubovskyi approved these changes

2021-02-23 11:32 UTC, merged