first commit
Ilya-brinchuk/jv-multithreading-01 pull request #2
Opened 2021-02-24 15:20 UTC by Ilya-brinchuk

2021-02-24 15:44 UTC, RuslanIbIsh approved these changes

2021-02-24 16:29 UTC, Sofasmile requested changes

2021-02-24 16:29 UTC, Sofasmile commented on src/main/java/ilya/multithreading/executor/Executor.java
> +public class Executor {
```suggestion
public class SumExecutorService {
```

2021-02-24 16:29 UTC, Sofasmile commented on src/test/java/ilya/multithreading/executor/ExecutorTest.java
> +    @Before
тут варто додати пусту строку між змінною і методом

2021-02-24 16:29 UTC, Sofasmile commented on src/test/java/ilya/multithreading/executor/ExecutorTest.java
> +    public void setUp() throws Exception {
не бажано прокидати Exception в тестах

2021-02-24 16:29 UTC, Sofasmile commented on src/test/java/ilya/multithreading/executor/ExecutorTest.java
> +    public void getSum_ok() {
на майбутнє, коли будеш виконувати тестове, одного тестового методу замало, варто покрити всі можливі сценарії, для даної домашки можеш залишити як є

2021-02-24 16:29 UTC, Sofasmile commented on src/test/java/ilya/multithreading/fork/ForkJoinerTest.java
> +}
не вистачає пустої строки)

2021-02-25 07:51 UTC, Sofasmile approved these changes

2021-02-25 10:30 UTC, merged